[package]
name = "fern_sim"
version = "0.1.0"
authors = ["Ozan Yıldız <developer@yildizozan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]